hubble: fix `cilium uninstall` if Hubble is disabled
[ cherry-picked from cilium/cilium-cli repository ]

Since commit 15910bdc1195 ("install: Disable hubble by default") Hubble
is disabled by default on installations with `cilium install`. This
leads to failures on `cilium uninstall` due to the fact that it tries to
disable Hubble first (regardless of whether it was previously enabled):

    $ cilium uninstall
    🔥 Deleting Relay...
    🔥 Deleting Relay certificates...
    ✨ Patching ConfigMap cilium-config to disable Hubble...
    Error: Unable to disable Hubble:  unable to patch ConfigMap cilium-config with patch "[{\"op\": \"remove\", \"path\": \"/data/hubble-tls-key-file\"},{\"op\": \"remove\", \"path\": \"/data/hubble-tls-client-ca-files\"},{\"op\": \"remove\", \"path\": \"/data/enable-hubble\"},{\"op\": \"remove\", \"path\": \"/data/hubble-socket-path\"},{\"op\": \"remove\", \"path\": \"/data/hubble-listen-address\"},{\"op\": \"remove\", \"path\": \"/data/hubble-disable-tls\"},{\"op\": \"remove\", \"path\": \"/data/hubble-tls-cert-file\"}]": the server rejected our request due to an error in our request

Handle this case more gracefully and check the ConfigMap entries before
attempting to patch them. This again allows to successfully run `cilium
uninstall` on a cluster with Hubble disabled:

    $ cilium status
        /¯¯\
     /¯¯\__/¯¯\    Cilium:         OK
     \__/¯¯\__/    Operator:       OK
     /¯¯\__/¯¯\    Hubble:         1 warnings
     \__/¯¯\__/    ClusterMesh:    OK
        \__/

    DaemonSet         cilium                   Desired: 2, Ready: 2/2, Available: 2/2
    Deployment        cilium-operator          Desired: 1, Ready: 1/1, Available: 1/1
    Deployment        clustermesh-apiserver    Desired: 1, Ready: 1/1, Available: 1/1
    Containers:       cilium-operator          Running: 1
                      clustermesh-apiserver    Running: 1
                      cilium                   Running: 2
    Image versions    cilium                   quay.io/cilium/cilium:v1.9.5: 2
                      cilium-operator          quay.io/cilium/operator-generic:v1.9.5: 1
                      clustermesh-apiserver    quay.io/coreos/etcd:v3.4.13: 1
                      clustermesh-apiserver    quay.io/cilium/clustermesh-apiserver:v1.9.5: 1
    Warnings:         hubble-relay             hubble-relay    hubble relay is not deployed

    $ cilium uninstall
    🔥 Deleting Relay...
    🔥 Deleting Relay certificates...
    ✨ Patching ConfigMap cilium-config to disable Hubble...
    ♻️  Restarted Cilium pods
    🔮 Auto-detected Kubernetes kind: GKE
    🔥 Deleting Service accounts...
    🔥 Deleting ConfigMap...
    🔥 Deleting Cluster roles...
    🔥 Deleting agent DaemonSet...
    🔥 Deleting operator Deployment...
    🔥 Deleting certificates...
    🔥 Deleting GKE Node Init DaemonSet...
    🔥 Deleting resource quotas...

Signed-off-by: Tobias Klauser <tobias@cilium.io>