test: Fix NodeCleanMetadata by using --overwrite
[ upstream commit 6a27fc16583927b476e3cef8b4ee048f3547e5f2 ]

Fixes the following errors:
```
cmd: "kubectl annotate nodes k8s1 io.cilium.network.ipv4-pod-cidr" exitCode: 1 duration: 76.869764ms stdout:

stderr:
error: at least one annotation update is required
```

Signed-off-by: Thomas Graf <thomas@cilium.io>
Signed-off-by: Joe Stringer <joe@cilium.io>