identity: deflake test TestGetIdentity
Currently, the test `TestGetIdentity` fails with the following error.

```
--- FAIL: TestGetIdentity (0.85s)
    --- FAIL: TestGetIdentity/Multiple_identities (0.26s)
        identity_test.go:226: Identity not found in the store
```

The reason is that the watch of the backend (started in its own
goroutine) might not be ready when the test starts to create test
identities.

Therefore, this commit introduces that the test waits with its
continuation until the watch is ready.

Fixes: #23856

Signed-off-by: Marco Hofstetter <marco.hofstetter@isovalent.com>