dpgen: improve error messages on incompatible maps
If an incompatible map error occurs due to a partial rebuild or a subtle bug
with build permutations, it can be difficult to figure out where the problem
lies exactly. By dumping successful files along with the name of the incoming
map and object, this becomes much easier to troubleshoot.

```
Error: "bpf_host.o" contains map "cilium_calls" incompatible with one or more
BPF objects [bpf_alignchecker.o]: max entries mismatch: 49 != 50
```

Signed-off-by: Timo Beckers <timo@isovalent.com>