cilium: bpf, fix undeclared ENCRYP_IFACE
[ upstream commit badc9beffe8efd66f040f6bfe08ca9c2cf283cd4 ]

level=warning msg="/var/lib/cilium/bpf/bpf_netdev.c:522:23: error: use of undeclared identifier 'ENCRYPT_IFACE'" subsys=daemon
level=warning msg="        fib_params.ifindex = ENCRYPT_IFACE;" subsys=daemon
level=warning msg="                             ^" subsys=daemon

Signed-off-by: John Fastabend <john.fastabend@gmail.com>
Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>