identity: deflake test TestGetIdentity
Currently, the test `TestGetIdentity` fails with the following error.

```
--- FAIL: TestGetIdentity (0.85s)
    --- FAIL: TestGetIdentity/Multiple_identities (0.26s)
        identity_test.go:226: Identity not found in the store
```

The reason is that the addition of the test identities might not be
reflected in the backend - even if we wait for some time in a wait loop.

Therefore, this commit introduces a proper wait with a sync.WaitGroup
before starting to check the identities in the backend.

Fixes: #23856

Signed-off-by: Marco Hofstetter <marco.hofstetter@isovalent.com>