doc: Upgrade MarkupSafe to 1.1.1
[ upstream commit 7a4e2bfeb5166e0af8ac11cbf82e01381ecd111a ]

Installing MarkupSafe 1.0.0 with setuptools 44.0.0 results in the
following error:

  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-0jhff9bc/MarkupSafe/setup.py", line 6, in <module>
      from setuptools import setup, Extension, Feature
  ImportError: cannot import name 'Feature' from 'setuptools'

Upgrading MarkupSafe to 1.1.1 solves the problem.

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>