ipam/multipool: Fix deletion of old CIDRs in updated pool
When a pool is updated, we have to loop over all the old CIDRs to remove
the ones that are not part of the latest version of the pool.

However, we should not immediately delete the removed CIDRs while
looping on them, because doing that interfere with the loop itself,
leading to incorrect results.  Instead we should mark each stale CIDR
and finally remove them from the slice later, once the loop is finished.

This can be proven by running the new unit test, that was failing before
this change:

=== RUN   TestUpdatePoolKeepOldCIDRs
    pool_allocator_test.go:1082:
        	Error Trace:	github.com/cilium/cilium/pkg/ipam/allocator/multipool/pool_allocator_test.go:1082
        	Error:      	Should be false
        	Test:       	TestUpdatePoolKeepOldCIDRs
--- FAIL: TestUpdatePoolKeepOldCIDRs (0.00s)

Signed-off-by: Fabio Falzoi <fabio.falzoi@isovalent.com>