cilium: don't invoke deprecated cilium daemon
Commit c7d4002534d6 ("Switch to spf13/cobra and spf13/viper to
implement CLI & config") split the daemon and the cli into two
separate binaries, as a result 'cilium daemon' doesn't exist
anymore. There are a few letfover spots in the test suite that
are using 'cilium daemon' and throwing error messages such as:

  # BENCHMARK=1 ./02-perf.sh
  [...]
  + cilium daemon config DropNotification=false Debug=false
  Error: unknown command "daemon" for "cilium"
  Run 'cilium --help' for usage.
  unknown command "daemon" for "cilium"
  [...]
  ++ cilium daemon config DropNotification=true Debug=true
  Error: unknown command "daemon" for "cilium"
  Run 'cilium --help' for usage.
  unknown command "daemon" for "cilium"
  [...]

Just drop the deprecated daemon command from these test cases,
and after that we get:

  [...]
  + cilium config DropNotification=false Debug=false
  + cilium endpoint config 63464 DropNotification=false Debug=false
  [...]

Fixes: c7d4002534d6 ("Switch to spf13/cobra and spf13/viper to implement CLI & config")
Signed-off-by: Daniel Borkmann <daniel@cilium.io>