helm: Fix patch failure when updating `hubble-generate-certs`
This PR fixes an issue with Helm upgrade of users who set
`hubble.tls.auto.method=cronJob`.

Because the definition of the `hubble-generate-certs` Kubernetes Job can
change between releases (as it did e.g. between 1.9 and 1.10), Helm will
try to patch in the changes in the Job object via Kubernetes API.
However, because the Job object is immutable, this PATCH request will
fail with the following error:

```
Error: UPGRADE FAILED: cannot patch "hubble-generate-certs" with kind Job
```

Because jobs are immutable, the way to update them is to delete the old
one and create a new one. While Helm does not seem to have a built-in
mechanism for this, we can achieve the same by changing the Job name
when its definition changes. This commit introduces such a logic, by
appending the checksum of the job spec to the job name. This will cause
the name of the job to change when the spec changes, and in turn cause
Helm to do delete the old job and replace it with a new one.

Fixes: #16316

Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>