bpf/sock: Fix renamed field
Use the backend 'flags' field instead the old 'pad'. This fixes bpf compilation fails when L7 LB is used, like this:

```
level=warning msg="/var/lib/cilium/bpf/bpf_sock.c:387:14: error: no member named 'pad' in 'struct lb4_backend'" subsys=datapath-loader
level=warning msg="                        l7backend.pad = 0;" subsys=datapath-loader
level=warning msg="                        ~~~~~~~~~ ^" subsys=datapath-loader
level=warning msg="1 error generated." subsys=datapath-loader
```

Add ENABLE_L7_LB to LB_OPTIONS in bpf/Makefile to catch this kind of errors in future.

Fixes: #18814
Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>