datapath: Fix redirect from L3 netdev to tunnel
[ upstream commit d4d3aa045993d5efb81af0cea173b37c528e9e30 ]

Previously, the redirect from L3 netdev (in nodeport.h) to Cilium's
tunnel device failed due to the bpf_redirect returning -ERANGE [1].

Further investigation revealed the following values for the troublesome
skb:

    skb->len = 60
    skb->data = 0x000000009566a77e
    skb->head = 0x000000001a70ff88
    skb->network_header = 64

"skb->data" was set to a weird location when compared to "skb->head",
and thus made the check to fail.

Adding the L2 hdr before redirecting to the tunnel device resolved the
issue.

P.S., I wanted to use "if (__ctx_is == __ctx_skb)" instead of the #if.
Unfortunately, then the bpf_xdp.c fails to compile with:

    error: use of undeclared identifier 'ENCAP_IFINDEX'

[1]: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/net/core/filter.c?h=v6.7.4#
n2147

Signed-off-by: Martynas Pumputis <m@lambda.lt>
Signed-off-by: Julian Wiedmann <jwi@isovalent.com>