dev-doctor: Update minimum helm version
[ upstream commit 4298879e53a2c9ff6bce3442920f9ab8b9d812da ]

Helm install may fail with following error on older versions -

`
Error: parse error at (cilium/templates/validate.yaml:38): unclosed action
`

Suggested-by: Chris Tarazi <chris@isovalent.com>
Signed-off-by: Aditi Ghag <aditi@cilium.io>
Signed-off-by: Louis DeLosSantos <louis.delos@isovalent.com>