bpf: Split handle_ipv4 in bpf_host.c after ct_lookup4
In order to reduce verifier complexity, split handle_ipv4 into two
functions chained by a tailcall. The first part will stop after doing
ct_lookup4 of the host firewall, and the second part will pick up the
results from a BPF map and go on.

The tailcall is saved, and the map is not used if host firewall is
disabled, so the overhead is minimal in this case.

Also move the "verifier workaround" call to revalidate_data in
handle_ipv4 to the ENABLE_HOST_FIREWALL section, as its presence at the
previous location now makes clang miscompile code and generate 32-bit
zero extension on pkt and pkt_end pointers, which is not accepted by the
verifier. Removing the workaround altogether leads to another verifier
error: "R5 invalid mem access 'scalar'".

Signed-off-by: Maxim Mikityanskiy <maxim@isovalent.com>