ci: disable cgo when installing Go toolchain
The LVH images don't have GCC, so we need to explicitly disable cgo.
This fixes the following failure:

	# runtime/cgo
	_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
	    3 | #include <stdlib.h>
	      |          ^~~~~~~~~~
	compilation terminated.

Fixes: bb3eec41c750 ("ci: run verifier tests with proper Go toolchain version")

Signed-off-by: Tobias Klauser <tobias@cilium.io>