pkg/maps/*: export Map{Key,Value} fields to fix cilium-dbg panics.
The `cilium-dbg map {get,list}` open-api handler will generically try to
unpack bpf map data into their respective key/value pairs.
However, if the Map{Key,Value} structs have unexported fields this will
panic causing the following errors:

level=warning msg="Cilium API handler panicked" client=@ method=GET panic_message="reflect: reflect.Value.SetUint using value obtained using unexported field" subsys=api url=/v1/map

This can be reproduced by enabling a feature that uses such a map, such
as `socketLB.enabled=true`, followed by doing a map list:

```
root@kind-worker:/home/cilium# cilium map list
Error: Get "http://localhost/v1/map": EOF
```

This commit exports any unexported fields in types used as key/values in
pkg/maps to avoid such errors.

Fixes: #33766

Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>