endpointmanager: deflake TestLookup
TestLookup could fail with

--- FAIL: Test (0.12s)
    --- FAIL: Test/EndpointManagerSuite (0.12s)
        --- FAIL: Test/EndpointManagerSuite/TestLookup (0.00s)
            manager_test.go:438:
                ... value *endpoint.Endpoint = &endpoint.Endpoint{[...]")
                ... Test Name: endpoint does not exist

In about 0.02% of the runs. Specifically, it would fail iff the endpoint
created happened to randomly get ID 1234, out of the pool of 4096 IDs.

Fix this by not creating an endpoint unconditionally in the test, so
that there is no chance of creating one with the "wrong" id.

Signed-off-by: David Bimmler <david.bimmler@isovalent.com>