bpf/tests: error when scapy pkts are > 1024 bytes
Commit e80be9ebff work-arounded the 128 byte limitation of the
cilium builtins implementation by reimplementing (hack, innefficiently
as noted in the commit msg) a simple version of memcpy/memcmp to be
used by scapy assert checks (only).

Unfortunately, when buffers exceed ~1036 bytes, the clang/LLVM optimizer
removes this code and (attempts to) use built-in instead (even at O1).
Since the builtin has a hard limit of 128 8-byte words [1] (thanks
Daniel Borkmann for the pointer), this leads to:

In file included from _scapy_selftest.c:12:
./scapy.h:64:23: error: A call to built-in function 'memcpy' is not supported.
   64 |                 *(__u64 *)(dst + i) = *(__u64 *)(src + i);
      |                                     ^
./scapy.h:64:23: error: A call to built-in function 'memcpy' is not supported.
./scapy.h:64:23: error: A call to built-in function 'memcpy' is not supported.
./scapy.h:64:23: error: A call to built-in function 'memcpy' is not supported.

or if directly using `__bpf_memcpy_builtin()` (which calls
`__builtin_memcpy()`):

In file included from _scapy_selftest.c:7:
In file included from ./pktgen.h:7:
/home/msuneclo/dev/cilium/bpf/include/bpf/builtins.h:165:2: error: A call to built-in function 'memcpy' is not supported.
  165 |         __builtin_memcpy(d, s, len);

Marking the memcpy/memset function as noopt either blows complexity
or stack limits, depending on the version.

Since I couldn't find (yet) a way to work-around this limitation,
make sure a meaningful error to developers is emitted if we are in
this specific situation.

[1] https://github.com/llvm/llvm-project/blob/a6929f7937696bb07788be6428fdcf1bf36775b5/llvm/lib/Target/BPF/BPFSelectionDAGInfo.h#L34

Signed-off-by: Marc Suñé <marc.sune@isovalent.com>
Reported-by: Simone Magnani <simone.magnani@isovalent.com>