bpf: Lift constraint for inline asm of static tail calls
In bpf_lxc, we now have static tail calls with HOST_EP_ID, a 'static
data' variable, as the index. Even though the value is known at compile
time, llc complains with:

    error: invalid operand for inline asm constraint 'i' at line 676688

We therefore need to lessen the constraint to allow for register
operands. The alternative would be to use a dynamic tail call, but that
is a lot more expensive.

Signed-off-by: Paul Chaignon <paul@cilium.io>