workflows/eks: Fix cluster name for scheduled runs
Commit 726967ce73a7 changed the cluster name in case of workflow_call to
include an additional number at the end. In case of scheduled runs
however, the number is undefined and we end up with a dash at the end.
Cilium then complains:

    🔮 Auto-detected Kubernetes kind: EKS
    ℹ️  Using Cilium version 1.19.0
    ℹ️  Using cluster name "cilium-cilium-18131028140-1-"
    🔮 Auto-detected kube-proxy has been installed

    Error: Unable to install Cilium: execution error at (cilium/templates/validate.yaml:159:5): The cluster name is invalid: must consist of lower case alphanumeric characters and '-', and must start and end with an alphanumeric character

This commit fixes it by moving the number to a different place in the
name.

Fixes: 726967ce73a7 ("workflows/eks: Allow multiple parallel runs from same PR")
Signed-off-by: Paul Chaignon <paul.chaignon@gmail.com>