helm: prevent failure on 1.17 upgrade from 1.16
Previously, the upgrade from helm chart 1.16 to
1.17-dev would fail because some values would
evaluate to nil due to changes in the default
values, printing errors like:

Error: UPGRADE FAILED: template:
cilium/templates/cilium-configmap.yaml:354:14:
executing "cilium/templates/cilium-configmap.yaml"
at <.Values.bpf.events.default.rateLimit>:
nil pointer evaluating interface {}.rateLimit

This change adds () to such values to prevent
nil pointer errors.

Signed-off-by: kema <github@kema.dev>