docs: Remove nodeinit instructions where unused
* The install/kubernetes/cilium/files/nodeinit/startup.bash template
  file is primarily dependent on explicit nodeinit configurations for it
  to have any effect, eg:
  * .Values.nodeinit.removeCbrBridge
  * .Values.nodeinit.reconfigureKubelet
  * .Values.gke.enabled ...
  * .Values.azure.enabled
  * .Values.nodeinit.revertReconfigureKubelet
* The install/kubernetes/cilium/files/nodeinit/prestop.bash template
  file is also similarly mainly dependent on other options, with one
  exception: it can delete the cilium_host device.

Given that the alibaba ENI, aws-cni, AWS ENI mode, and kind installation
instructions don't configure these other options, the nodeinit daemonset
does not need to be installed on these systems. The only case that
should differ is upon shutdown of the nodeinit DS, which doesn't fully
clean up Cilium state anyway so users should use 'cilium uninstall' CLI
to clean up such clusters.

Signed-off-by: Joe Stringer <joe@cilium.io>