vendor: Revert cilium/ebpf to v0.17.1
The Cilium eBPF library v0.17.2 broke CLI compilation on the main branch:

    $ make -C cilium-cli local-release
    ...
    Building release binary for darwin/amd64...
    # github.com/cilium/cilium/pkg/datapath/linux/probes
    Error: ../pkg/datapath/linux/probes/attach_type.go:28:21: undefined: features.HaveProgramType
    Error: ../pkg/datapath/linux/probes/probes.go:351:18: undefined: features.HaveProgramHelper
    Error: ../pkg/datapath/linux/probes/probes.go:365:18: undefined: features.HaveLargeInstructions
    Error: ../pkg/datapath/linux/probes/probes.go:379:18: undefined: features.HaveBoundedLoops
    Error: ../pkg/datapath/linux/probes/probes.go:393:18: undefined: features.HaveProgramHelper
    Error: ../pkg/datapath/linux/probes/probes.go:400:18: undefined: features.HaveProgramHelper
    Error: ../pkg/datapath/linux/probes/probes.go:407:18: undefined: features.HaveV2ISA
    Error: ../pkg/datapath/linux/probes/probes.go:421:18: undefined: features.HaveV3ISA

Revert to the older version until it is fixed.

Signed-off-by: Joe Stringer <joe@cilium.io>