cli: fix policy parsing failures in cm policy inspection cmd
This commit fixes failures observed in clustermesh
'inspect-policy-default-local-cluster' command due to policy parsing
failures. The failure happens because during parsing the policy object
is validated, which depends on certain global config options. Currently,
the command doesn't populate these config parameters leading to
validation failure. One such failure mode is policies with
FromNodes/ToNodes selectors which are only valid when
`node-selector-labels` config is enabled.

```
$ cilium config set enable-node-selector-labels true --restart

$ cat <<EOF | kubectl apply -f -
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: from-node-cnp
spec:
  endpointSelector:
    matchLabels:
      app: netshoot
  ingress:
  - fromNodes:
    - matchLabels:
        node-role.kubernetes.io/control-plane: ""
EOF

$ cilium clustermesh inspect-policy-default-local-cluster

Error: Unable to inspect policy default local cluster: Error parsing Cilium network policies: Invalid CiliumNetworkPolicy spec: FromNodes/ToNodes rules can only be applied when the "enable-node-selector-labels" flag is set
```

This commit introduces the change to populate the relevant config
options by parsing data from cilium config map ensuring that parsing
behavior is same as that in daemon/operator.

Signed-off-by: Deepesh Pathak <deepeshpathak09@gmail.com>