auth: use 1024-bit RSA key in test
Starting with Go 1.24 RSA key sizes below 1024 lead to an error being
returned by rsa.GenerateKey by default[^1] which makes
TestSpireDelegateClient_GetCertificateForIdentity when running it using
Go 1.24:

    --- FAIL: TestSpireDelegateClient_GetCertificateForIdentity (0.00s)
        certificate_provider_test.go:279: failed to generate leaf key: crypto/rsa: 512-bit keys are insecure (see https://go.dev/pkg/crypto/rsa#hdr-Minimum_key_size)
    FAIL
    FAIL	github.com/cilium/cilium/pkg/auth/spire	0.006s
    FAIL

Fix this by using an 1024-bit RSA key in the test.

[^1]: https://go.dev/doc/go1.24#cryptorsapkgcryptorsa

Signed-off-by: Tobias Klauser <tobias@cilium.io>