bpf: fix native local build
Setting HOST_CC and HOST_STRIP on environments that are not
cross-compiled results in a failed compilation such as:

```
x86_64-linux-gnu-gcc -Wall -O2 -Wno-format-truncation -I include/ cilium-probe-kernel-hz.c -o cilium-probe-kernel-hz
cilium-probe-kernel-hz.c:6:10: fatal error: stdio.h: No such file or directory
    6 | #include <stdio.h>
      |          ^~~~~~~~~
```

Thus, HOST_CC and HOST_STRIP are only set when cross-compilation is
being performed.

Fixes: 9f05489ad35f ("build: Fix cross compiling for amd64 on arm64")
Signed-off-by: André Martins <andre@cilium.io>