endpointmanager: fix data races in tests accessing endpoint labels
Fix data races caused by accessing (*Endpoint).OpLabels without holding
(*Endpoint).mutex, e.g.

==================
WARNING: DATA RACE
Read at 0x00c0014002a0 by goroutine 181:
  maps.Copy[go.shape.map[string]github.com/cilium/cilium/pkg/labels.Label,go.shape.map[string]github.com/cilium/cilium/pkg/labels.Label,go.shape.string,go.shape.struct { Key string "json:\"key\""; Value string "json:\"value,omitempty\""; Source string "json:\"source\""; github.com/cilium/cilium/pkg/labels.cidr *net/netip.Prefix "json:\"-\"" }]()
      /usr/local/go/src/maps/maps.go:63 +0xfb8
  github.com/cilium/cilium/pkg/labels.(*OpLabels).IdentityLabels()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/labels/oplabels.go:80 +0xe79
  github.com/cilium/cilium/pkg/endpointmanager.TestMissingNodeLabelsUpdate()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager_test.go:946 +0xb10
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1851 +0x44

Previous write at 0x00c0014002a0 by goroutine 188:
  github.com/cilium/cilium/pkg/labels.Labels.upsertLabel()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/labels/oplabels.go:215 +0x687
  github.com/cilium/cilium/pkg/labels.(*OpLabels).ReplaceIdentityLabels()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/labels/oplabels.go:133 +0x392
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).replaceIdentityLabels()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1192 +0x84
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).SetIdentity()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:1033 +0x1eb
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).identityLabelsChanged()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2265 +0x1291
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runIdentityResolver.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2127 +0x51
  github.com/cilium/cilium/pkg/controller.(*controller).runController()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/controller/controller.go:251 +0x9c
  github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked.gowrap1()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/controller/manager.go:116 +0xbc

Goroutine 181 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1851 +0x8f2
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2279 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1792 +0x225
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2277 +0x96c
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2142 +0xeea
  main.main()
      _testmain.go:81 +0x164

Goroutine 188 (running) created at:
  github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/controller/manager.go:116 +0x777
  github.com/cilium/cilium/pkg/controller.(*Manager).updateController()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/controller/manager.go:89 +0x54f
  github.com/cilium/cilium/pkg/controller.(*Manager).UpdateController()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/controller/manager.go:53 +0xe8f
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runIdentityResolver()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2123 +0xcf5
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).ModifyIdentityLabels()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1938 +0x66a
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).UpdateLabelsFrom()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2068 +0x104
  github.com/cilium/cilium/pkg/endpointmanager.(*endpointManager).updateHostEndpointLabels()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpointmanager/host.go:61 +0x7b
  github.com/cilium/cilium/pkg/endpointmanager.(*endpointManager).startNodeLabelsObserver.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpointmanager/host.go:42 +0x8a4
  github.com/cilium/stream.Multicast[go.shape.struct { github.com/cilium/cilium/pkg/node/types.Node; OptOutNodeEncryption bool; UID k8s.io/apimachinery/pkg/types.UID; ProviderID string; IPv4NativeRoutingCIDR *github.com/cilium/cilium/pkg/cidr.CIDR; IPv6NativeRoutingCIDR *github.com/cilium/cilium/pkg/cidr.CIDR; IPv4Loopback net.IP }].func1()
      /home/tklauser/go/src/github.com/cilium/cilium/vendor/github.com/cilium/stream/sources.go:205 +0x2d4
  github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Update()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/node/local_node_store.go:210 +0x1b6
  github.com/cilium/cilium/pkg/endpointmanager.TestMissingNodeLabelsUpdate()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager_test.go:943 +0xa8e
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1851 +0x44
==================
--- FAIL: TestMissingNodeLabelsUpdate (0.01s)

Signed-off-by: Tobias Klauser <tobias@cilium.io>