ipsec: Fix unit tests for per-tunnel keys
The IPsec unit tests were previously running with global keys. Since
support for such keys was removed, they will now run with per-tunnel
keys. They however currently fail with per-tunnel keys:

    --- FAIL: TestUpsertIPSecEndpoint (0.00s)
    panic: runtime error: slice bounds out of range [:36] with capacity 14 [recovered]
        panic: runtime error: slice bounds out of range [:36] with capacity 14

This is because the fake boot ID being used is shorter than 36
characters. We need to pass a fake boot ID that is as long as a real
boot ID to fix this.

In addition the expected XFRM's mark must now include the node ID to
match what is installed on the system.

Finally, the expected XFRM state keys have changed and are derived from
the global key instead of simply being the global key.

Signed-off-by: Paul Chaignon <paul.chaignon@gmail.com>