bpf/Makefile: Move global config options to MAX_BASE_OPTIONS
Unless an option maximizes program size in a BPF program and minimizes
it in another, there is no good reason to define global options in each
MAX_*_OPTIONS. This commit instead moves all global options to
MAX_BASE_OPTIONS.

This commit also fixes several options that were missing for bpf_host
(ENABLE_HOSTPORT, ENABLE_SRC_RANGE_CHECK, and ENABLE_IPV4_FRAMENTS).

ENABLE_EGRESS_GATEWAY is kept in each MAX_*_OPTIONS macro because it
can't be enabled for bpf_xdp or we'd get the following compilation
errors:

    In file included from bpf_xdp.c:38:
    /cilium/bpf/lib/nodeport.h:1108:20: error: no member named 'ifindex' in 'struct xdp_md'
                    if (info && ctx->ifindex != ENCAP_IFINDEX) {
                                ~~~  ^
    /cilium/bpf/lib/nodeport.h:1108:31: error: use of undeclared identifier 'ENCAP_IFINDEX'; did you mean 'CB_IFINDEX'?
                    if (info && ctx->ifindex != ENCAP_IFINDEX) {
                                                ^~~~~~~~~~~~~
                                                CB_IFINDEX
    /cilium/bpf/lib/common.h:599:2: note: 'CB_IFINDEX' declared here
            CB_IFINDEX,
            ^
    2 errors generated.
    make: *** [Makefile:188: bpf_xdp.ll] Error 1

Signed-off-by: Paul Chaignon <paul@cilium.io>