bpf: specify handle_lxc_traffic return type to fix -Wimplicit-int error
This fixes the following error when building with clang 15:

    bpf_host.c:1414:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
    handle_lxc_traffic(struct __ctx_buff *ctx)
    ^
    1 error generated.

Fixes: a4aac43d1ed7 ("bpf: Support hostfw with endpoint routes")

Signed-off-by: Tobias Klauser <tobias@cilium.io>