gateway: Sync up the experimental conformance test
This is to fix the below issue, which was missed in the PR #31005.

```
     experimental_conformance_test.go:117: error creating experimental conformance test suite: no kind is registered for the type v1.CustomResourceDefinitionList in scheme "k8s.io/client-go/kubernetes/scheme/register.go:80"
--- FAIL: TestExperimentalConformance (0.00s)
```

Fixes: https://github.com/cilium/cilium/pull/31005
Signed-off-by: Tam Mach <tam.mach@cilium.io>