workflows: Fix Hubble flow capture in smoke tests
The step "Capture cilium-sysdump" currently fails in smoke tests with:

    gzip: stdin: not in gzip format
    tar: Child returned status 1
    tar: Error is not recoverable: exiting now
    Error: Process completed with exit code 2.

This is happening because we attempt to download the latest hubble
binary at URL github.com/cilium/hubble/releases/download/latest and fail
to decompress the downloaded file. That's because the downloaded file
contains only "Not found".

Indeed, URL cilium/hubble/releases/download/latest doesn't exist, the
correct URL is cilium/hubble/releases/latest/download. Nevermind that
other releases are downloaded at
github.com/cilium/hubble/releases/download/$TAG ¯\_(ツ)_/¯

Fixes: 0cbb855a (".github: Capture hubble flows when smoke test fails")
Signed-off-by: Paul Chaignon <paul@cilium.io>