resource: Fix queue entry coalescing
The entries added to the resource's workqueue were added as pointers which
messes up the comparisons causing coalescing to not happen. This causes
TestResource_Retries to flake sometimes with:

  	Error:  Not equal:
		expected: 5
        	actual  : 10
        Test:       	TestResource_Retries
        Messages:   	expected to see 5 retries for update

What happens is that the key gets requeued as &updateEntry{key}, which
doesn't match with the previous one &updateEntry{key}, so it's effectively
a new entry with it's own rate limiting and retry count state and thus
we end up seeing more retries than expected.

This fixes the issue by adding the entries by value. The comparisons of
syncEntry and updateEntry are now trivially correct. The deleteEntry carries
the pointer to the last known state of the deleted object, but this is fine
since there can only be one such object.

Signed-off-by: Jussi Maki <jussi@isovalent.com>