cilium-health: Fix status cmd nil pointer derefence
Adds a check to the command client and instead fails with
an error message if it is nil.

Example:
```

vagrant@runtime1:~$ cilium-health status  -d
Error: Invalid combination of arguments
```

Fixes #5779

Signed-off-by: ifeanyi <ify1992@yahoo.com>