test: Delete hubble-ca-secret when cleaning up
Remove hubble-ca-secret when cleaning up Cilium components. Otherwise
tests can fail installing Cilium with this error message:

  Error: rendered manifests contain a resource that already
  exists. Unable to continue with install: existing resource conflict:
  kind: Secret, namespace: kube-system, name: hubble-ca-secret

Add a clean up call to the Cilium install code to clean up any
resources that may be left behind after kubectl delete on the cilium
yaml.

Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>