docs: Update docs with minimum helm version
[ upstream commit a831b3e299c6b938404eee280cc4274c8a56f0ed ]

Helm install may fail with following error on older versions -

`
Error: parse error at (cilium/templates/validate.yaml:38): unclosed action
`

Suggested-by: Chris Tarazi <chris@isovalent.com>
Signed-off-by: Aditi Ghag <aditi@cilium.io>
Signed-off-by: Louis DeLosSantos <louis.delos@isovalent.com>