bpf/tests/scapy: support pkts 1036-1518 bytes
Commit e80be9ebff work-arounded the 128 byte limitation of the
cilium builtins implementation by reimplementing (hack, innefficiently
as noted in the commit msg) a simple version of memcpy/memcmp to be
used by scapy assert checks (only).

Unfortunately, when buffers exceed ~1036 bytes, the clang/LLVM optimizer
removes memcpy code and (attempts to) use built-in instead (even at O1).
Since the builtin has a hard limit of 128 8-byte words [1] (thanks
Daniel Borkmann for the pointer), this leads to:

In file included from _scapy_selftest.c:12:
./scapy.h:64:23: error: A call to built-in function 'memcpy' is not supported.
   64 |                 *(__u64 *)(dst + i) = *(__u64 *)(src + i);
      |                                     ^
./scapy.h:64:23: error: A call to built-in function 'memcpy' is not supported.
./scapy.h:64:23: error: A call to built-in function 'memcpy' is not supported.
./scapy.h:64:23: error: A call to built-in function 'memcpy' is not supported.

or if directly using `__bpf_memcpy_builtin()` (which calls
`__builtin_memcpy()`):

In file included from _scapy_selftest.c:7:
In file included from ./pktgen.h:7:
/home/msuneclo/dev/cilium/bpf/include/bpf/builtins.h:165:2: error: A call to built-in function 'memcpy' is not supported.
  165 |         __builtin_memcpy(d, s, len);

This commit works-around this issue too by wrapping the original
_scapy_memcpy() to perform chunked memcpys. Current packet size is limited to
1518 bytes (__SCAPY_MAX_BUF), but could be extended to 2K.

[1] https://github.com/llvm/llvm-project/blob/a6929f7937696bb07788be6428fdcf1bf36775b5/llvm/lib/Target/BPF/BPFSelectionDAGInfo.h#L34

Signed-off-by: Marc Suñé <marc.sune@isovalent.com>
Reported-by: Simone Magnani <simone.magnani@isovalent.com>