l7lb: fix registration of flag loadbalancer-l7
[ upstream commit 40f2d3fa8ada336fa1b9e318a1840c2872bd5b75 ]

Currently, the flag `loadbalancer-l7` isn't properly registered.

Even though it's working fine when reading the config property from
the Cilium Configmap, it's not working when trying to use the
flag as Go flag.

```
2024-10-29T16:24:26Z debug layer=debugger Adding target 23 "/usr/bin/cilium-operator-generic-bin --config-dir=/tmp/cilium/config-map --debug=true --loadbalancer-l7=envoy"
Error: unknown flag: --loadbalancer-l7
```

Therefore, this commit is moving the config property into the respective
Hive Cell where it gets properly registered.

Reported-by: André Martins <andre@cilium.io>
Signed-off-by: Marco Hofstetter <marco.hofstetter@isovalent.com>
Signed-off-by: Jussi Maki <jussi@isovalent.com>