kvstore/store: Fix staticchecker warnings
Fixes the following warnings:
pkg/kvstore/store/store.go:83:20: error strings should not be capitalized (ST1005)
pkg/kvstore/store/store.go:451:20: error strings should not be capitalized (ST1005)
pkg/kvstore/store/store.go:460:2: should use for range instead of for { select {} } (S1000)
pkg/kvstore/store/store_test.go:77:5: var testType is unused (U1000)

Signed-off-by: Thomas Graf <thomas@cilium.io>