endpoint: add unit test covering handleOutdatedPodInformer
Introduce a new unit test to cover the handleOutdatedPodInformer
function, in preparation for the subsequent changes. In particular,
this proves two problems currently affecting it:

1. The function does not propagate the error returned by the fetch
   function if the endpoint UID is not set.
2. The function does not perform any retry in case of pod UID
   mismatch, conversely to the intended behavior.

--- FAIL: TestHandleOutdatedPodInformer (0.00s)
    --- FAIL: TestHandleOutdatedPodInformer/pod_not_found_(epUID:_) (0.00s)
        endpoint_test.go:278:
                Error Trace:    .../daemon/cmd/endpoint_test.go:278
                Error:          Not equal:
                                expected: *errors.StatusError(&errors.StatusError{...
                                actual  : <nil>(<nil>)
                Test:           TestHandleOutdatedPodInformer/pod_not_found_(epUID:_)
    --- FAIL: TestHandleOutdatedPodInformer/uid_mismatch_(epUID:_uid) (0.00s)
        endpoint_test.go:288:
                Error Trace:    .../daemon/cmd/endpoint_test.go:288
                Error:          Not equal:
                                expected: 0x14
                                actual  : 0x1
                Test:           TestHandleOutdatedPodInformer/uid_mismatch_(epUID:_uid)
                Messages:       Incorrect number of retries
    --- FAIL: TestHandleOutdatedPodInformer/uid_mismatch,_then_resolved_(epUID:_uid) (0.00s)
        endpoint_test.go:278:
                Error Trace:    .../daemon/cmd/endpoint_test.go:278
                Error:          Not equal:
                                expected: <nil>(<nil>)
                                actual  : *errors.errorString(&errors.errorString{s:"pod store outdated"})
                Test:           TestHandleOutdatedPodInformer/uid_mismatch,_then_resolved_(epUID:_uid)
        endpoint_test.go:288:
                Error Trace:    .../daemon/cmd/endpoint_test.go:288
                Error:          Not equal:
                                expected: 0x6
                                actual  : 0x1
                Test:           TestHandleOutdatedPodInformer/uid_mismatch,_then_resolved_(epUID:_uid)
                Messages:       Incorrect number of retries
FAIL
FAIL    github.com/cilium/cilium/daemon/cmd     1.336s
FAIL

Related: f6606c6ccdb8 ("daemon,endpoint,cni: Pass pod UID through CNI ADD")
Signed-off-by: Marco Iorio <marco.iorio@isovalent.com>