dbg: increase limit when safely reading envoy metrics via cilium-dbg
Currently, fetching the Envoy metrics via `cilium-dbg envoy admin metrics`
can end up easily with the following exception.

```
/home/cilium# cilium-dbg envoy admin metrics
Error: cannot get metrics: failed to read "stats/prometheus" response: read limit reached
```

The reason is the current limit of 1MB when reading the response body
with `safeio.ReadAllLimit`.

Therefore, this commit is increasing the limit to `100MB`.

Signed-off-by: Marco Hofstetter <marco.hofstetter@isovalent.com>