bpf: fix build with the latest LLVM 15.0.0git
With the latest LLVM 15.0.0git build breaks with

    bpf_host.c:1414:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
    handle_lxc_traffic(struct __ctx_buff *ctx)
    ^

Add the missing return type explicitly, as dictated by -Wimplicit-int.

Fixes: a4aac43d1e ("bpf: Support hostfw with endpoint routes")

Signed-off-by: Anton Protopopov <aspsk@isovalent.com>