kvstore: Fix staticchecker warnings
Fixes the following warnings:
pkg/kvstore/backend.go:38:6: type backendBase is unused (U1000)
pkg/kvstore/base_test.go:236:6: func drainEvents is unused (U1000)
pkg/kvstore/events.go:71:6: type signalChan is unused (U1000)
pkg/kvstore/events.go:94:29: should use make(stopChan) instead (S1019)
pkg/kvstore/lock.go:122:19: error strings should not be capitalized (ST1005)
pkg/kvstore/logfields.go:53:2: const fieldLease is unused (U1000)
pkg/kvstore/logfields.go:56:2: const fieldTTL is unused (U1000)

Signed-off-by: Thomas Graf <thomas@cilium.io>