ingress: Fix conformance test for host rule
This commit is to fix the below errors from conformance test. Basically,
ingress with spec.tls doesn't enforce https i.e. http request is still
going through. Kindly note that the conformance test for ingress is
expected the same behavior. Hence, we need to add http listener in Service
and update CEC with listener filter accordingly.

Also, for security reason, enforcing https feature is added for http
listener. User can still disable such restriction via feature flag
--enforce-ingress-https.

Thanks to Nicolas, Duffie and Chris for clarification.

```
Failed steps:

  Scenario: An Ingress with a host rule should not route traffic when hostname does not match # features/host_rules.feature:64
    When I send a "GET" request to "http://subdomain.bar.com" # features/host_rules.feature:67
      Error: Get "http://10.98.35.160/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

  Scenario: An Ingress with a wildcard host rule should send traffic to the matching backend service # features/host_rules.feature:70
    When I send a "GET" request to "http://bar.foo.com" # features/host_rules.feature:73
      Error: Get "http://10.103.158.100/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

  Scenario: An Ingress with a wildcard host rule should not route traffic matching no dns label # features/host_rules.feature:84
    When I send a "GET" request to "http://foo.com" # features/host_rules.feature:87
      Error: Get "http://10.103.107.12/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

5 scenarios (2 passed, 3 failed)
37 steps (29 passed, 3 failed, 5 skipped)
1m45.93343714s
```

Testing for enforcing http redirect

```
$ curl -s --cacert local/minica.pem https://bookinfo.cilium.rocks/details/1 | jq
{
  "id": 1,
  "author": "William Shakespeare",
  "year": 1595,
  "type": "paperback",
  "pages": 200,
  "publisher": "PublisherA",
  "language": "English",
  "ISBN-10": "1234567890",
  "ISBN-13": "123-1234567890"
}

$ curl -s --cacert local/minica.pem -v http://bookinfo.cilium.rocks/details/1 | jq
*   Trying 10.111.49.122:80...
* Connected to bookinfo.cilium.rocks (10.111.49.122) port 80 (#0)
> GET /details/1 HTTP/1.1
> Host: bookinfo.cilium.rocks
> User-Agent: curl/7.82.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 308 Moved Permanently
< location: https://bookinfo.cilium.rocks/details/1
< date: Mon, 11 Apr 2022 06:45:31 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host bookinfo.cilium.rocks left intact

```

Relates to #19306

Signed-off-by: Tam Mach <tam.mach@isovalent.com>