Ginkgo: Fix var initialization
Issue in the current master branch on all ginkgo test, introduced in commit
e024f7f341f96515f7687a48d132082267c3848a

Error:
````
10:09:27 [K8s-1.6] k8sT/Nightly.go:149:27: undefined: ciliumPath
10:09:27 [K8s-1.6] k8sT/Nightly.go:152:25: undefined: ciliumPath
```

Build ID: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/521/

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>