daemon: sleep 2 seconds before fatal
[ upstream commit ac97bb14a8d12312d5f8a0dff6f24880bddc1713 ]

If the user specifies a flag that does not exist to cilium-agent it can
make Cilium to present the following error to the user:
```
PostStartHookError: command '/cni-install.sh' exited with 126:
```

This is misleading and the reason for it to happen is because
cni-install.sh was not completed by the time `cilium-agent` process
exited. For this reason, before printing the helper message and / or
fatal, Cilium will be delayed 2 seconds so it gives enough time for
`cni-install.sh` to complete and the user will see a different type of
error in the pod status message.

Signed-off-by: Ray Bejjani <ray@isovalent.com>
Signed-off-by: André Martins <andre@cilium.io>
Signed-off-by: Ian Vernon <ian@cilium.io>