bpf: Fix CGO import warning
The golang compilation would previously print this warning while
compiling the daemon, because "bpf_htons" would not be declared when
importing the conntrack header file from CGO:

$ make -C daemon
  CHECK contrib/scripts/bindata.sh
  GO    daemon/cilium-agent
In file included from /home/joe/work/src/github.com/cilium/cilium/bpf/lib/conntrack.h:24:0,
                 from ../pkg/alignchecker/alignchecker.go:30:
/home/joe/work/src/github.com/cilium/cilium/bpf/lib/common.h: In function ‘conn_is_dns’:
/home/joe/work/src/github.com/cilium/cilium/bpf/lib/common.h:532:15: warning: implicit declaration of function ‘bpf_htons’ [-Wimplicit-function-declaration]

Fix this by shifting the function into a file which includes utils.h.

Developers may need to run the following command to clear out their CGO
caches to pick up these changes and silence the warning:

    $ go clean -cache

Signed-off-by: Joe Stringer <joe@covalent.io>