test: Overwrite existing taint when labeling nodes with NoSchedule
Martynas reported that the following error occurs:
```
      unable label nodes: unable to taint node with 'kubectl taint nodes k8s3 key=value:NoSchedule': Exitcode: 1
      Stdout:
      Stderr:
         error: node k8s3 already has key taint(s) with same effect(s) and --overwrite is false
```

.. when the option `--cilium.provision=false` is used

Fixes: 014fd8e41ae ("test: Decouple node labeling from node names")
Signed-off-by: Thomas Graf <thomas@cilium.io>