test: Move policy examples validation to container
There's no need to run this minimal linting / cilium policy validation
from the runtime VM; replace it with a simple docker run of a bash
script from the docs-builder image.

This will help to avoid out-of-sync issues between dependencies in the
Cilium tree and the Cilium packer ci VMs used to run runtime tests. It
should also speed up the jenkins runs slightly.

Examples failures are easier to debug, too:

JSON:

    $ make -C Documentation check
    ...
      CHECK Documentation examples
    Error: Validation of policy /src/examples/policies/l3/simple/l3.json has failed: malformed policy, not JSON?

    make: *** [Makefile:29: check] Error 1

YAML:

    $ make -C Documentation check
    ...
    /src/examples/crds/ciliumendpoints.yaml
      56:1      error    too many blank lines (1 > 0)  (empty-lines)

    make: *** [Makefile:29: check] Error 1

Signed-off-by: Joe Stringer <joe@cilium.io>