ci: bypass proxy.golang.org in Go toolchain installation
[ upstream commit e263ddf6a6f39e91d19fa69881641a2bb25187f3 ]

Directly access golang.org/dl to avoid errors such as

> go: golang.org/dl/go1.21.4@latest: module golang.org/dl/go1.21.4: Get "https://proxy.golang.org/golang.org/dl/go1.21.4/@v/list": dial tcp: lookup proxy.golang.org on 127.0.0.53:53: server misbehaving
> Error: Process completed with exit code 1.

Reported-by: Julian Wiedmann <jwi@isovalent.com>
Signed-off-by: Tobias Klauser <tobias@cilium.io>
Signed-off-by: Marco Iorio <marco.iorio@isovalent.com>