checkpatch: Update image digest
[ upstream commit c232aaf3d827eef586b15f682f13a4fb14fdbc98 ]

The `image-tools` CI is supposed to only build an image if there isn't
already a tag for the last commit that changed that image
directory on quay.io.

There seem to have been an issue with this check in [this job](https://github.com/cilium/image-tools/actions/runs/17178799757/job/48738420427) for the
`checkpatch` image causing the job to fail to check for the existing
tag, assume it didn't exist and proceed to rebuild it:

> /usr/local/bin/crane
> 2025/08/23 18:59:33 HEAD request failed, falling back on GET: error getting credentials - err: exit status 1, out: `ANY_REGISTRY_USERNAME is not set`
> Error: error getting credentials - err: exit status 1, out: `ANY_REGISTRY_USERNAME is not set`
> error: crane returned 1
> quay.io/cilium/cilium-checkpatch:1755701578-b97bd7a doesn't exist

With the `1755701578-b97bd7a` tag rebuilt and repushed, quay.io must have
garbage collected the previous image digest with the same tag, causing pulls of
the previous digest for that tag to start failing ([example](https://github.com/cilium/cilium/actions/runs/17182063773/job/48745850927?pr=41345#step:3:16)):

> docker: Error response from daemon: manifest for quay.io/cilium/cilium-checkpatch@sha256:edc094e3c306bbf9b9481f5a99aa6e8e00539cd1f4f7f7f4ffefeeabb0ff88b5 not found: manifest unknown: manifest unknown

Signed-off-by: Hadrien Patte <hadrien.patte@datadoghq.com>
Signed-off-by: viktor-kurchenko <viktor.kurchenko@isovalent.com>