bpf: drop const qualifier from srv6_load_meta_sid's sid argument
Running `make -C bpf` with my local LLVM 21 toolchain results in the following
error:

```
In file included from bpf_lxc.c:51:
./lib/srv6.h:418:27: error: variable 'dst_sid' is uninitialized when passed as a const pointer argument
      here [-Werror,-Wuninitialized-const-pointer]
  418 |         srv6_load_meta_sid(ctx, &dst_sid);
      |                                  ^~~~~~~
1 error generated.
```

Drop the const qualifier from srv6_load_meta_sid's sid argument. The function
wraps ctx_load_meta_ipv6, which doesn't take a const pointer and does actually
mutate the pointed-to object, so this is not super useful.

Found a similar case in curl/curl#18420 since -Wuninitialized-const-pointer was
only just added to LLVM.

Signed-off-by: Timo Beckers <timo@isovalent.com>