github: Increase workflow timeout
Increase conformance-gke timeout to avoid fail due to cancelled test
as in:

installation-and-connectivity
cancelled 2 hours ago in 30m 13s


[=] Test [client-egress]
....
[=] Test [echo-ingress]
Error: The operation was canceled.

Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>