workflows: Fix use of paths-filter on master pushes
For pull requests, paths-filter retrieves the list of changed files via
the GitHub API, but for pushes it needs access to the code. When a
workflow is triggered by a push to master, we therefore need to checkout
the source code before using paths-filter.

This change fixes the errors:

    Run dorny/paths-filter@78ab00f87740f82aec8ed8826eb4c3c851044126
    Get current git ref
      /usr/bin/git branch --show-current
      fatal: not a git repository (or any of the parent directories): .git
    Error: The process '/usr/bin/git' failed with exit code 128

Reported-by: André Martins <andre@cilium.io>
Signed-off-by: Paul Chaignon <paul@cilium.io>