gha: Bump minimum gke versions
As per today, k8s 1.24 is no longer available for new cluster, hence we
need to bump versions to avoid the below issue.

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.24" found.
```

Related note: https://cloud.google.com/kubernetes-engine/docs/release-notes#January_26_2024

Signed-off-by: Tam Mach <tam.mach@cilium.io>