test: Remove Cilium after pods deleted in K8sBandwidthTest
Previously, after running the K8sBandwidthTest suite, the netperf pods
were removed after Cilium agent removal which could lead to "Pods are
still not deleted after a timeout: 4m0s timeout expired".

The timeout was due to kubelet failing to find the Cilium's CNI binary:

    error killing pod: failed to "KillPodSandbox" for
    X with KillPodSandboxError: "rpc
    error: code = Unknown desc = networkPlugin cni failed to teardown pod
    "netperf-pod" network: failed to find plugin
    "cilium-cni" in path [/opt/cni/bin]"

Fix this by removing Cilium only after removing the pods.

Signed-off-by: Martynas Pumputis <m@lambda.lt>