option: Check nodePortMax < ephermeralPortMin in agent
[ upstream commit 1099ecfea1535d38417ceb2bba44e4b4438ea260 ]

Previously, if the ephermeral range min port was not greater than the
nodeport range max port, the compilation of bpf_netdev was failing with
a cryptic message:

    level=warning msg="In file included from /var/lib/cilium/bpf/bpf_overlay.c:39:" subsys=daemon
    level=warning msg="/var/lib/cilium/bpf/lib/nodeport.h:898:3: error: array size is negative" subsys=daemon
    level=warning msg="                build_bug_on(!(NODEPORT_PORT_MAX < EPHERMERAL_MIN));" subsys=daemon
    level=warning msg="
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" subsys=daemon
    level=warning msg="/var/lib/cilium/bpf/lib/utils.h:124:45: note: expanded from macro 'build_bug_on'" subsys=daemon
    level=warning msg="# define build_bug_on(e) ((void)sizeof(char[1 - 2*!!(e)]))" subsys=daemon
    level=warning msg=" ^~~~~~~~~~~" subsys=daemon
    level=warning msg="3 warnings and 1 error generated." subsys=daemon

Fix this by checking the constraint in the agent, and log a helpful
message how to fix it.

Signed-off-by: Martynas Pumputis <m@lambda.lt>
Signed-off-by: Maciej Kwiek <maciej@isovalent.com>