contrib/scripts: Fix IndexError in stacktrace script
[ upstream commit cad0ac186755ecc2fa587f8439abf6d1e477d1a8 ]

Since the below mentioned commit, it seems that other usages of
`source_dir` were not fixed up when it became a string var instead of an
slice var. Fix the remaining usages. Now the script outputs the full
output.

```
$ ./consolidate_go_stacktrace.py --filter lock ...
...
Stacktraces from the following packages were skipped as they do not match ['lock', 'Lock(', 'RLock(', 'Semacquire(']:
Traceback (most recent call last):
  File "/home/chris/code/cilium/cilium/contrib/scripts/consolidate_go_stacktrace.py", line 185, in <module>
    args.source_dir[0]),
    ~~~~~~~~~~~~~~~^^^
IndexError: string index out of range
```

Fixes: bafbfb8452d ("consolidate_go_stacktrace.py: Use relative paths by default")

Signed-off-by: Chris Tarazi <chris@isovalent.com>
Signed-off-by: Fabio Falzoi <fabio.falzoi@isovalent.com>