bpf: Fix complexity test
Somehow, easier changes caused the compiler to emit bogus bytecode. This
results in the following error:
```
        verifier_test.go:242: Error: program tail_nodeport_ipv6_dsr: load program: permission denied: 283: (71) r2 = *(u8 *)(r4 +14): R4 invalid mem access 'inv' (422 line(s) omitted)
        Verifier error tail: load program: permission denied:
        	(414 line(s) omitted)
        	279: (dc) r3 = be32 r3
        	; .icmp6_mtu	= bpf_htonl(THIS_MTU - ohead),
        	280: (63) *(u32 *)(r10 -124) = r3
        	281: (b7) r2 = 2
        	; struct icmp6hdr icmp __align_stack_8 = {
        	282: (63) *(u32 *)(r10 -128) = r2
        	; .priority	= ip6->priority,
        	283: (71) r2 = *(u8 *)(r4 +14)
        	R4 invalid mem access 'inv'
        	processed 231 insns (limit 1000000) max_states_per_insn 1 total_states 10 peak_states 10 mark_read 4
```

Apparently the compiler thinks it can place `ip6` in R4, but the
verifier found a code path where this isn't the case. The hope is that
by declaring the original allocation volatile, the compiler will read
from the stack every time.

Signed-off-by: Dylan Reimerink <dylan.reimerink@isovalent.com>