bpf: specify handle_srv6 return type to fix -Wimplicit-int error
This fixes the following error when building with clang 15:

    bpf_host.c:1055:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
    handle_srv6(struct __ctx_buff *ctx)

Fixes: f42a49011ca7 ("bpf: Perform SRv6 policy lookup")

Signed-off-by: Tobias Klauser <tobias@cilium.io>