dynamicconfig: Fix flake in TestDynamicConfigMap
The test case uses multiple reflectors for ConfigMap which is
problematic as the k8s fake client uses a single channel for events
and thus with multiple watchers events get lost:

  $ go test -c
  $ stress -count 1000 ./dynamicconfig.test -test.run TestDynamicConfigMap
  /tmp/go-stress-20250508T120956-1349213616
  --- FAIL: TestDynamicConfigMap (2.02s)
  --- FAIL: TestDynamicConfigMap/default (2.01s)
  logger.go:256: time=2025-05-08T12:09:57.194+02:00 level=INFO source=/home/jussi/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/hive.go:357 msg="Starting hive"
  logger.go:256: time=2025-05-08T12:09:57.194+02:00 level=INFO source=/home/jussi/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/hive.go:361 msg="Started hive" duration=59.227µs
  logger.go:256: time=2025-05-08T12:09:57.198+02:00 level=WARN source=/home/jussi/go/src/github.com/cilium/cilium/pkg/k8s/client/fake.go:501 msg="Multiple watches for resource intercepted. This highlights a potential cause for flakes" module=k8s-fake-client resource=v1.configmaps
  table_test.go:189: waiting for confing table: timeout reached while waiting for condition

Fix the test by not starting the Hive until after the ConfigMap
objects have been created. This way no Watch events are created
and we get all the objects with the initial List().

  $ ,stress -count 10000 ./dynamicconfig.test -test.run TestDynamicConfigMap
  33s: 10000 runs total, 0 failures

Signed-off-by: Jussi Maki <jussi@isovalent.com>