.github: Consistently clean up workers on start
[ upstream commit c8cb040f93835dd7b34b571b30b9ecd5da6b09fb ]

[ backporter's notes: cover the remaining cases in this stable branch. ]

We recently started experiencing reports that there's not enough disk space.
For example, on CI image build runs, I observed the following error
while building a docker container image for a PR in the merge queue:

  Error: buildx failed with: ERROR: failed to solve:
  ResourceExhausted: failed to compute cache key:
  mount callback failed on /tmp/containerd-mount2956800340:
  write /tmp/containerd-mount2956800340/usr/lib/x86_64-linux-gnu/libc.so.6:
  no space left on device

Several workflows were already unconditionally calling the clean up
script as an early step during the corresponding set up job. Update the
remaining users of the script to also unconditionally run the script.

Signed-off-by: Joe Stringer <joe@cilium.io>
Signed-off-by: Julian Wiedmann <jwi@isovalent.com>