cilium-cli/clustermesh: Fix bad type for service type
Helm expects /clustermesh/apiserver/service/type to be a string
according to install/kubernetes/cilium/values.schema.json:1404, but
it was passed as a v1.ServiceType causing the following error:

```
cilium clustermesh enable --context cluster1
🔮 Auto-exposing service within Azure VPC (service.beta.kubernetes.io/azure-load-balancer-internal)

Error: Unable to enable ClusterMesh: values don't meet the specifications of the schema(s) in the following chart(s):
cilium:
- at '/clustermesh/apiserver/service/type': invalid jsonType v1.ServiceType
```

This is fixed by casting it to a string.

Fixes: 112e08d4b37b ("clustermesh: fix hardcode at service type")

Signed-off-by: Mauricio Vásquez <mauriciov@microsoft.com>