l4lb: Support environments with existing veth
GitHub environments recently started locating multiple virtual ethernet
devices as part of this lookup command, which causes the test to fail
with:

    +[21:48:53] LB_VETH_HOST='vethc63b890
    veth9368ee0'
    +[21:48:53] ip l set dev vethc63b890 veth9368ee0 xdp obj bpf_xdp_veth_host.o
    Error: either "dev" is duplicate, or "veth9368ee0" is a garbage.
    Error: Process completed with exit code 255.

Fix it by iterating through the veths.

Signed-off-by: Joe Stringer <joe@cilium.io>