bpf: nodeport: clean up stack allocation for dsr_reply_icmp4()
[ upstream commit c954094143da7da3009a4b5e6df7c9cd9aedf676 ]

With the subsequent patch I was suddenly getting a

```
error: unsupported dynamic stack allocation
```

from this code location. Simplify things a bit to help the compiler.

Signed-off-by: Julian Wiedmann <jwi@isovalent.com>
Signed-off-by: Antony Reynaud <antony.reynaud@isovalent.com>