Ginkgo: Test Flake on RuntimeValidatedConntrack
This test was failed randonmly in the last two days because pods were
not ready after a new change was applied.

Test log:

```
level=debug msg="running command: sudo cilium config PolicyEnforcement=default"
cmd: "sudo cilium config PolicyEnforcement=default" exitCode: 0

level=debug msg="running command: sudo cilium endpoint list -o jsonpath='{range [?(@.labels.orchestration-identity[0]!=\"reserved:health\")]}{@.container-name}{\"=\"}{@.id}{\"\\n\"}{end}'"
cmd: "sudo cilium endpoint list -o jsonpath='{range [?(@.labels.orchestration-identity[0]!=\"reserved:health\")]}{@.container-name}{\"=\"}{@.id}{\"\\n\"}{end}'" exitCode: 0
 client=12075
server=14594
server-2=19080
server-3=20084
netcat=27624
client-2=28707

level=debug msg="running command: sudo cilium endpoint config 28707 IngressPolicy=false"
cmd: "sudo cilium endpoint config 28707 IngressPolicy=false" exitCode: 0
 Endpoint 28707 configuration updated successfully

level=debug msg="running command: sudo cilium endpoint config 28707 EgressPolicy=false"
cmd: "sudo cilium endpoint config 28707 EgressPolicy=false" exitCode: 0
 Endpoint 28707 configuration updated successfully

level=debug msg="running command: sudo cilium endpoint config 12075 IngressPolicy=false"
cmd: "sudo cilium endpoint config 12075 IngressPolicy=false" exitCode: 0
 Endpoint 12075 configuration updated successfully

level=debug msg="running command: sudo cilium endpoint config 12075 EgressPolicy=false"
cmd: "sudo cilium endpoint config 12075 EgressPolicy=false" exitCode: 0
 Endpoint 12075 configuration updated successfully

level=debug msg="running command: sudo cilium endpoint config 14594 IngressPolicy=false"
cmd: "sudo cilium endpoint config 14594 IngressPolicy=false" exitCode: 1
 Error: Cannot update endpoint 14594: [PATCH /endpoint/{id}/config][500] patchEndpointIdConfigFailed  unable to regenerate endpoint program because state transition to waiting-to-regenerate was unsuccessful; check `cilium endpoint log 14594` for more information
```

This error happened on:

- https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/1633/testReport/
- https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/1632/testReport/
- https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/1631/testReport/
- https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/1630/testReport/

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>