ci: reduce envoy idle connection timeout to 3s for e2e upgrade workflow
[ upstream commit 4d7691c2b34337b2f0a28b4c05e516a211dda7e2 ]

This commit sets the default value of envoy idle connection timeout to a
low value of 3s(default: 60s). This is required to not leak unencrypted
packets generated during upstream connection teradown of connectivity
test.

Currently the upgrade workflow runs L7 traffic interruption tests(1) on
cilium restart and then runs a check for encrypted packet validation(2)
during cilium downgrade. The envoy upstream connection created for HTTP
requests during the first step is closed after the idle connection
timeout(60s). If this teardown happens after the unencrypted packet
probe is attached, the check fails because of unencrypted packets from
TCP connection termination sequence.

```
Error: bpftrace output is not empty
[08:53:22:884861] [0xffff88810764e600]  ↳ 10.244.1.28:47662 -> 10.244.3.85:8000 (proto: 6, len: 52, ifindex: 9, netns: effffff9, srcPod: 1 (internal: 0), dstPod: 1 (internal: 0), proxy: 0 (masqueraded: 0))
[08:53:22:884861] [0xffff88810764e600]   ↳ TCP (TCPFlags: ...A...F, Seq: 1164909021, Ack: 3975956836)
[08:53:22:888636] [0xffff88810764e600]  ↳ 10.244.3.85:8000 -> 10.244.1.28:47662 (proto: 6, len: 52, ifindex: 7, netns: effffff9, srcPod: 1 (internal: 0), dstPod: 1 (internal: 0), proxy: 0 (masqueraded: 0))
[08:53:22:888636] [0xffff88810764e600]   ↳ TCP (TCPFlags: ...A...F, Seq: 3975956836, Ack: 1164909022)
[08:53:22:888680] [0xffff888330839900]  ↳ 10.244.1.28:47662 -> 10.244.3.85:8000 (proto: 6, len: 52, ifindex: 9, netns: effffff9, srcPod: 1 (internal: 0), dstPod: 1 (internal: 0), proxy: 0 (masqueraded: 0))
[08:53:22:888680] [0xffff888330839900]   ↳ TCP (TCPFlags: ...A...., Seq: 1164909022, Ack: 3975956837)
```

 This change reduces idle connection timeout(to 3s) to give upstream
 connection termination resonable deadline so that encryption check is not
 impacted.

Signed-off-by: Deepesh Pathak <deepeshpathak09@gmail.com>