proxyports: Use require.Eventually instead of time.Sleep in tests
Use require.Eventually to wait for the proxy port to be released for up
to 100 ms in order to avoid test flakes like:

time="2024-12-05T10:03:53.750539537Z" level=info msg="Adding new proxy port rules for listener1:14623" id=listener1 subsys=proxy
    proxyports_test.go:155:
        	Error Trace:	/host/pkg/proxy/proxyports/proxyports_test.go:155
        	Error:      	Not equal:
        	            	expected: 0
        	            	actual  : 1
        	Test:       	TestPortAllocator

Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>