docs: Update kube-router getting started guide
[ upstream commit dcaaca27d7662f3b1aceb5827ab344b50e9a7694 ]

- Use the latest version of kube-router (v0.4.0). Otherwise, the
  installation of it fails with:
    error: unable to recognize "generic-kuberouter-only-advertise-routes.yaml":
    no matches for kind "DaemonSet" in version "extensions/v1beta1"
- Put args into quotes to be consistent with kube-router's DaemonSet file.
- Update connectivity check output.

Signed-off-by: Martynas Pumputis <m@lambda.lt>
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>