pkg/policy: show error if user installs a L7 CNP with L7 proxy disabled
[ upstream commit 70296ae60704ee4ed5d8571e0e96a1ce717c8ddf ]

A cilium node with a L7 proxy enabled will show the following status
in the node status:

```
status:
  nodes:
    k8s1:
      enforcing: true
      lastUpdated: "2019-10-29T14:09:49.449575508Z"
      localPolicyRevision: 2
      ok: true
```

A cilium node without a L7 proxy enabled will show the following status
in the node status:

```
status:
  nodes:
    k8s1:
      error: 'Invalid CiliumNetworkPolicy spec: L7 policy is not supported since L7
        proxy is not enabled'
      lastUpdated: "2019-10-29T14:12:23.309604539Z"
```

Signed-off-by: André Martins <andre@cilium.io>
Signed-off-by: Ray Bejjani <ray@isovalent.com>