test/fuzzing: Fix fuzzing test failure
```
pkg/policy/rule_test_fuzz.go:57:10: td.repo.mustAdd undefined (type *Repository has no field or method mustAdd)
...
pkg/policy/repository_test_fuzz.go:59:84: undefined: lbls
pkg/policy/repository_test_fuzz.go:2374:18: undefined: fooIdentity
pkg/policy/repository_test_fuzz.go:2382:68: undefined: fooIdentity
pkg/policy/repository_test_fuzz.go:2390:18: undefined: fooIdentity
pkg/policy/repository_test_fuzz.go:2398:68: undefined: fooIdentity
pkg/policy/repository_test_fuzz.go:2408:19: undefined: fooIdentity
pkg/policy/repository_test_fuzz.go:2421:69: undefined: fooIdentity
...
pkg/policy/resolve_test_fuzz.go:130:39: undefined: generateCIDREgressRule
pkg/policy/resolve_test_fuzz.go:136:16: undefined: generateCIDRIdentities
pkg/policy/resolve_test_fuzz.go:521:35: emptyMapState().withState undefined (type mapState has no field or method withState)
pkg/policy/resolve_test_fuzz.go:694:35: emptyMapState().withState undefined (type mapState has no field or method withState)
pkg/policy/resolve_test_fuzz.go:699:102: rule1MapStateEntry.withExplicitAuth undefined (type mapStateEntry has no field or method withExplicitAuth)
pkg/policy/resolve_test_fuzz.go:699:119: undefined: AuthTypeDisabled
pkg/policy/resolve_test_fuzz.go:700:102: rule1MapStateEntry.withExplicitAuth undefined (type mapStateEntry has no field or method withExplicitAuth)
pkg/policy/resolve_test_fuzz.go:700:119: undefined: AuthTypeDisabled
pkg/policy/resolve_test_fuzz.go:718:3: undefined: ingressKey
pkg/policy/resolve_test_fuzz.go:719:3: undefined: ingressKey
```

Fix by including the path with the policy repository `mustAdd()`
function in the fuzzing script and where the above variables are
defined, so that it's in scope when the fuzzer is run.

Ref: https://github.com/cilium/cilium/actions/runs/12862705459/workflow
Fixes: d036ef2021 ("pkg/policy: convert rule_test.go to use Lookup")

Signed-off-by: Chris Tarazi <chris@isovalent.com>