bpf,nodeport: Evaluate the hook input
nodeport_nat_egress_ipv4_hook and nodeport_rev_dnat_ipv4_hook is defined
as a macro and we substitute it to the constant value. This kills the
compile-time check for the input value entirely. The input value is not
type-checked or we can even use the undeclared variable like the bug in
the previous commit. To avoid such a mistake. Evaluate the input value
properly. The following is an example for detecting the error in the
previous commit.

```
./lib/nodeport.h:2488:48: error: use of undeclared identifier 'info'
 2488 |         ret = nodeport_nat_egress_ipv4_hook(ctx, ip4, info->sec_identity, &tuple, l4_off, &ext_err);
```

Signed-off-by: Yutaro Hayakawa <yutaro.hayakawa@isovalent.com>