make: Silence error on `make render-docs`
[ upstream commit 66bb75f6da70f25115ee1340a3665fb792269533 ]

docker container rm -f docs-cilium >/dev/null
Error: No such container: docs-cilium
make: [render-docs] Error 1 (ignored)

Signed-off-by: Thomas Graf <thomas@cilium.io>