Vagrantfiles: excluding packaging docker/stage for rsync
By adding the replacing the docker image build command with `make
docker-image` in commit 3380ba98b9 it caused concurrent issues with
rsync on the sambe base path among multiple VMs printing messages such
as [1]. Thus this commit excludes the faulty directory:
`contrib/packaging/docker/stage`.

[1]
```
Error: file has vanished: "/root/jenkins/workspace/cilium_cilium_PR-
980-AMWMANE5I6SHMDMUG3VFIE2B2UTSP3OHZOSEKQPS7WG6244I7MSQ/contrib/
packaging/docker/cilium-0.9.90/vendor/gopkg.in/yaml.v2/LICENSE.libyaml"
```

Signed-off-by: André Martins <andre@cilium.io>