endpoint: Fix ENABLE_NAT46 endpoint config validation
[ upstream commit d98532619159054cd666b2720ff66a9d12cfd8bf ]

Previously, the validation function of the ENABLE_NAT46 field
did not check a given value and it assumed that the function
is called whenever a caller wants to enable NAT46.

This was not always the case. E.g. `cilium endpoint config $EPID
ConntrackLocal Enabled` did not specify the field, but the request
handler was anyway calling the validation function for the field with
value "Disabled" which resulted in a response with the 400 error code:

    Error: Cannot update endpoint 1923: [PATCH /endpoint/{id}/config][400]
    patchEndpointIdConfigInvalid

Signed-off-by: Martynas Pumputis <m@lambda.lt>
Signed-off-by: Joe Stringer <joe@cilium.io>