cilium: Fix missing error log dump from compilation
When compilation fails in Cilium, it currently does not dump the actual
compilation error. This is in particular annoying given the developer
experience suffers from it if an error cannot be reproduced otherwise.

Turns out this got changed via 6882e98baf7c ("datapath: always generate
BTF debug information") where it switched from `compileAndLink(ctx, prog,
dir, debug, args...)` to unconditional `compileAndLink(ctx, prog, dir,
true, args...)` which then accidentially made the warning messages
disappear from regular (non-debug) mode in the scopedLog selector.

Before looking into this, I was not aware that these would show up in
debug mode. Make this a plain log.Warn given this is something we should
warn about and have easy introspection no matter if in debug or non-debug
mode.

Before fix:

  [...]
  level=error msg="Failed to compile bpf_host.dbg.o: exit status 1" compiler-pid=3097802 linker-pid=3097803 subsys=datapath-loader
  level=error msg="BPF template object creation failed" bpfHeaderfileHash=b67b2d6708b2cb48f42dc6305e5802be6fba717325a2006082c3a0b396e67630 error="failed to compile template program /var/run/cilium/state/templates/b67b2d6708b2cb48f42dc6305e5802be6fba717325a2006082c3a0b396e67630: Failed to compile bpf_host.dbg.o: exit status 1" subsys=datapath-loader
  [...]

After fix:

  [...]
  level=error msg="Failed to compile bpf_host.dbg.o: exit status 1" compiler-pid=3086249 linker-pid=3086250 subsys=datapath-loader
  level=warning msg="In file included from /var/lib/cilium/bpf/bpf_host.c:55:" subsys=datapath-loader
  level=warning msg="/var/lib/cilium/bpf/lib/nodeport.h:570:8: error: implicit declaration of function 'fib_redirect_v6' [-Werror,-Wimplicit-function-declaration]" subsys=datapath-loader
  level=warning msg="        ret = fib_redirect_v6(ctx, l3_off, ip6, ctx_get_ifindex(ctx), &oif);" subsys=datapath-loader
  level=warning msg="              ^" subsys=datapath-loader
  level=warning msg="/var/lib/cilium/bpf/lib/nodeport.h:601:8: error: implicit declaration of function 'fib_redirect_v4' [-Werror,-Wimplicit-function-declaration]" subsys=datapath-loader
  level=warning msg="        ret = fib_redirect_v4(ctx, l3_off, ip4, ctx_get_ifindex(ctx), &oif);" subsys=datapath-loader
  level=warning msg="              ^" subsys=datapath-loader
  level=warning msg="2 errors generated." subsys=datapath-loader
  level=error msg="BPF template object creation failed" bpfHeaderfileHash=b67b2d6708b2cb48f42dc6305e5802be6fba717325a2006082c3a0b396e67630 error="failed to compile template program /var/run/cilium/state/templates/b67b2d6708b2cb48f42dc6305e5802be6fba717325a2006082c3a0b396e67630: Failed to compile bpf_host.dbg.o: exit status 1" subsys=datapath-loader
  [...]

Fixes: 6882e98baf7c ("datapath: always generate BTF debug information")
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>