alignchecker: fix LLVM 15 build by removing an unused variable
With LLVM 15 build breaks with

    bpf_alignchecker.c:47:6: error: variable 'iter' set but not used [-Werror,-Wunused-but-set-variable]
        int iter = 0;
            ^

The iter variable was intended to help to declare structures with names s0, s1,
etc., but instead all the structures were named "siter":

    DECLARE(struct, ipv4_ct_tuple, iter)

expands to

    {
        struct ipv4_ct_tuple siter = {};
        trace_printk("%p", 1, &siter);
        iter++
    }

Remove the unused variable and simplify the DECLARE macro to take only one
argument, so a new type check can be added, e.g., in the following way:

    DECLARE(struct ipv4_ct_tuple)

Fixes: 006ebebc28e ("bpf: Adjust alignchecker to avoid stack limits")

Signed-off-by: Anton Protopopov <a.s.protopopov@gmail.com>