daemon: sockops: delay sockops init till node_config.h gets generated
[ upstream commit fc25dbe2454815456cefab4f34807ab3ec270b47 ]

SockmapEnable and SkmsgEnable require node_config.h which generated
in Daemon.init().

level=error msg="Failed to compile bpf_sockops.o: exit status 1" compiler-pid=23550 linker-pid=23551 subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/sockops/bpf_sockops.c:21:10: fatal error: 'node_config.h' file not found" subsys=datapath-loader
level=warning msg="#include <node_config.h>" subsys=datapath-loader
level=warning msg="         ^~~~~~~~~~~~~~~" subsys=datapath-loader
level=warning msg="1 error generated." subsys=datapath-loader
level=error msg="failed compile sockops/bpf_sockops.c: Failed to compile bpf_sockops.o: exit status 1" subsys=sockops
level=error msg="Failed to compile bpf_redir.o: exit status 1" compiler-pid=23553 linker-pid=23554 subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/sockops/bpf_redir.c:21:10: fatal error: 'node_config.h' file not found" subsys=datapath-loader
level=warning msg="#include <node_config.h>" subsys=datapath-loader
level=warning msg="         ^~~~~~~~~~~~~~~" subsys=datapath-loader

Fixes: ac55c6a (daemon: Create BPF maps before restoring service IDs)

Signed-off-by: Nirmoy Das <ndas@suse.de>
Signed-off-by: John Fastabend <john.fastabend@gmail.com>