helm: Fix preflight check resource quota conflict
[ upstream commit bc126ef09bf852f2ae8e7f394281da4efdaa10aa ]

This commit fixes the preflight check on GKE which currently conflicts
with the resource quotas that may be present from an already installed
Cilium version:

```
Error: rendered manifests contain a resource that already exists. Unable
to continue with install: existing resource conflict: kind:
ResourceQuota, namespace: cilium, name: cilium-resource-quota
```

Fixes: 14ff743b5bb6 ("gke: add resource quotas for Cilium namespace")

Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>
Signed-off-by: Deepesh Pathak <deepshpathak@gmail.com>