cilium: use %v for dumping frontend struct on error
Lets not pretend we try to make users happy with small Haikus on service
update errors. ;-) The U+7532 is dumped due to the service port:

  # ./cilium/cilium service update --frontend "8.8.8.8:30002" --backends "10.12.164.240:80" --id 3
  Updating existing service with id '3'
  Error: Cannot add/update service: [PUT /service/{id}][500] putServiceIdFailure  Unable to allocate service ID 3 for {{"8.8.8.8" {"TCP" '甲'}} '\x03'}: Service ID 3 is already registered to "192.168.178.29:30002"

Use %v instead of %q format string to fix it:

  # ./cilium/cilium service update --frontend "8.8.8.8:30002" --backends "10.12.164.240:80" --id 3
  Updating existing service with id '3'
  Error: Cannot add/update service: [PUT /service/{id}][500] putServiceIdFailure  Unable to allocate service ID 3 for {{8.8.8.8 {TCP 30002}} 3}: Service ID 3 is already registered to "192.168.178.29:30002"

Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>