k8s: Use InsertOrderedMap in StateDB reflector
We need to retain the initial ordering of events by key to not end up
for example processing Update(A), Delete(B) in the wrong order when
there are data dependencies between the two (e.g. A reuses the IP in B).

Extend the tests to catch this problem. Without the fix the tests fail
reliably with:
    Error Trace:    /home/jussi/go/src/github.com/cilium/cilium/pkg/k8s/statedb_test.go:372
                                            /home/jussi/go/src/github.com/cilium/cilium/pkg/k8s/statedb_test.go:177
    Error:          Not equal:
                    expected: "obj1"
                    actual  : "obj2"

Fixes: 1166e1c2b7b8 ("k8s: Reflector for reflecting ListerWatcher into StateDB table")
Signed-off-by: Jussi Maki <jussi@isovalent.com>