Fix helm template for hubble-relay prometheus annotations
We introduced a templating bug when adding prometheus annotations for
hubble-relay. `{ { .Values.hubble.relay.prometheus.port | quote } }`
will be rendered as is because of the spaces between the braces, which
results in a helm templating error when enabling relay metrics without
service monitors.

```
Error: YAML parse error on cilium/templates/hubble-relay/deployment.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.hubble.relay.prometheus.port | quote":interface {}(nil)}
```

Fixes: e4abda5aba37 ("enable Prometheus metrics for Hubble Relay")

Signed-off-by: Fabian Fischer <fabian.fischer@isovalent.com>