bpf: Make nodeport_snat_fwd_ipv6 global
This is a preparatory commit address stack limit
issues in the tail_handle_snat_fwd_ipv6 call chain as
we hit the BPF stack limit.
By making nodeport_snat_fwd_ipv6 global, its stack
variables are allocated in a separate frame rather than
being merged into the caller’s frame.

```
/go/src/github.com/cilium/cilium/bpf/lib/nodeport_egress.h:61:23: error: Looks like the BPF stack limit is exceeded. Please move large on stack variables into BPF per-cpu array map. For non-kernel uses, the stack can be increased using -mllvm -bpf-stack-size.

   61 |         struct ipv6_ct_tuple tuple = {};
:
/go/src/github.com/cilium/cilium/bpf/lib/nodeport_egress.h:57:25: error: Looks like the BPF stack limit is exceeded.
   57 |         struct ipv6_nat_target target = {
      |

```

Signed-off-by: Aditi Ghag <aditi@cilium.io>