endpoint: fix incorrect RLock usage in controller
[ upstream commit b176f8283b5c0a93d70f3652cbc2a129bcd10186 ]

The below commit accidentally replaced a call to `LockAlive` with `RLockAlive`.
This resulted in the endpoint mutex having `Unlock` called when the endpoint
mutex was `RLocked`, which caused the following error:

```
fatal error: sync: Unlock of unlocked RWMutex

goroutine 996 [running]:
runtime.throw(0x2d25cea, 0x20)
    /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc000cdcd30 sp=0xc000cdcd00 pc=0x108fd72
sync.throw(0x2d25cea, 0x20)
    /usr/local/go/src/runtime/panic.go:594 +0x35 fp=0xc000cdcd50 sp=0xc000cdcd30 pc=0x108fcf5
sync.(*RWMutex).Unlock(0xc000f62004)
    /usr/local/go/src/sync/rwmutex.go:124 +0xa1 fp=0xc000cdcd80 sp=0xc000cdcd50 pc=0x10c98e1
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Unlock(0xc000f62000)
```

Fixes: 8eb1698b2 ("endpoint: Avoid harmless controller failures when endpoint disappears")

Signed-off by: Ian Vernon <ian@cilium.io>

Signed-off-by: Ian Vernon <ian@cilium.io>