cilium: probe and enable LPM map in prefilter
Right now only /32 or /128 prefixes can be added to Cilium's prefilter:

  # ./cilium/cilium prefilter list
  Revision: 3
  1.1.1.1/32
  1.1.1.2/32
  # ./cilium/cilium prefilter update --cidr="1.1.1.2/16"
  Error: Cannot add/update prefilter: [PATCH /prefilter][500] patchPrefilterFailure  No map enabled for CIDR string 1.1.0.0/16

The reason was that back then we didn't have a get_next_key for LPM maps
yet and therefore they couldn't be dumped from the kernel. Add a probe
and enable it as these days 4.16+ kernels support this facility.

Fixes: #9379
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>