docs: Fix "make render-docs" permissions issue
Some versions of docker, when passed the `--volume` flag, will create
the directory *as root* before launching the container, which caused
`make render-docs` to fail with a permissions issue like the following:

  Exception occurred:
    File "/usr/local/lib/python3.7/os.py", line 221, in makedirs
      mkdir(name, mode)
  PermissionError: [Errno 13] Permission denied: '/src/Documentation/_build/doctrees'

Fix it by creating the directory as the current user first.

Fixes: #10869

Signed-off-by: Joe Stringer <joe@cilium.io>