test: ensure kubectl version is available for test run
[ upstream commit 61812551f6594cf27d4f2ca61d0b96208826b911 ]

[ Backporter's notes: All hunks needed conflict resolution. Mostly just
    including the new code into the older version of the branch. Also needed
    to resolve these errors:
    $ make -C test/ build
    config/config.go:82:2: undefined: flagset
    helpers/kubectl.go:274:4: undefined: ginkgoext.Failf
    helpers/kubectl.go:3154:46: res.GetStdOut().String undefined
        (type string has no field or method String)
]

This change makes K8s ginkgo test suite download kubectl version
compatible with current cluster version if it's not available.

Signed-off-by: Maciej Kwiek <maciej@isovalent.com>
Signed-off-by: Joe Stringer <joe@cilium.io>