cnp: reject l3-dependent l7 rule if proxy does not support it
The user will be able to check the current status of the policy by doing
kubectl describe cnp <policy-name> and will the following message:

```
Nodes:
  Cilium - K 8 S - Master:
    Error:         Selected proxy "oxy" is not able to enforce this rule. Please start cilium with a capable l7 proxy (e.g. "envoy")
    Last Updated:  2017-12-04T08:17:08.86067385-08:00
  Cilium - K 8 S - Node - 2:
    Last Updated:  2017-12-04T06:53:57.465031766-08:00
    Ok:            true
```

Signed-off-by: André Martins <andre@cilium.io>