k8s: Fix parsing of CCNPs
Host policies are rejected on master with the following error:

    $ kubectl describe ccnp | tail -n9
    Status:
      Nodes:
        k8s1:
          Error:         Invalid CiliumNetworkPolicy spec: rule cannot have NodeSelector
          Last Updated:  2020-08-10T12:52:51Z
        k8s2:
          Error:         Invalid CiliumNetworkPolicy spec: rule cannot have NodeSelector
          Last Updated:  2020-08-10T12:52:48Z
    Events:              <none>

This error is printed because CiliumNetworkPolicy.Parse() has some new
checks to prevent using NodeSelector in CNPs. It assumes
CiliumClusterwideNetworkPolicy.Parse() will be called in the case of CCNPs
with NodeSelectors. However, the k8s watcher for CCNPs calls
addCiliumNetworkPolicyV2 which takes a types.SlimCNP and therefore calls
CiliumNetworkPolicy.Parse().

This commit implements a temporary fix for this regression by manually
construction a CCNP object from CiliumNetworkPolicy.Parse() when the
namespace is empty (CNP is actually a CCNP) and parsing that instead of
the CNP object. It also adds a new unit test to check this behavior.

Related: #12834
Fixes: eafeb8f ("k8s: Disallow nodeSelector for CNP at agent level")
Signed-off-by: Paul Chaignon <paul@cilium.io>