ingress: Fix conformance test for matching orders
If an ingress with a mixed path rules (e.g. Exact, Prefix), the Exact
route must have higher priority. While ordering in Ingress spec is not
important, Envoy is checking routes in order i.e. if a route is match,
no further route checks are made. Hence, in order to conform with Ingress,
we need to sort Envoy routes to make sure that all Path Routes (i.e. Exact) is
always come first.

```
Failed steps:

  Scenario: An Ingress with mixed path rules should send traffic to the matching backend service where Exact is preferred # features/path_rules.feature:174
    And the response must be served by the "foo-exact" service # features/path_rules.feature:179
      Error: expected the request to be served by foo-exact but it was served by foo-prefix

```

Relates to #19306

Signed-off-by: Tam Mach <tam.mach@isovalent.com>