bpf: some clang versions have unused var error in alignment check
bpf_alignchecker.c:47:6: error: variable 'iter' set but not used [-Werror,-Wunused-but-set-variable]
        int iter = 0;
            ^

Fix by marking maybe_unused.

Signed-off-by: John Fastabend <john.fastabend@gmail.com>