loader: add message if error is ENOTSUP
[ upstream commit 64364477fc024e8026e30016257fa124fca4a901 ]

I was trying to install cilium in a machine without a vxlan module
available. Add a helpful message for the next time this happens.

Tested by running:
> PRIVILEGED_TESTS=1 go test  -test.v -test.run TestSetupTunnelDevice

on said machine, and got the following output:
...

```
        Error:          Received unexpected error: setting up vxlan device: creating vxlan device: creating device cilium_vxlan: operation not supported, maybe kernel module for vxlan is not available?
	Test:           TestSetupTunnelDevice/Vxlan
```

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>
Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>