github: reinstall Cilium with the same chart
Use the same chart that was used in install in the reinstall.

This avoids the problem where the values used in the original install
would not be accepted by the outdated charts, e.g.:

Run helm upgrade cilium ./install/kubernetes/cilium \
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
cilium:
- at '/envoy/xdsMode': value must be one of '', 'split', 'ads', 'strict-ads'

Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>