k8s: Make optional CiliumPodIPPool fields a pointer
This changes the Golang definition of the CilumPodIPPool type to use
pointers instead of values for the IPv4/IPv6 fields. This is required
because those fields are marked as optional in our kubebuilder
annotations, but the fields of the structs themselves are required.

This caused an issue that it was not possible to create or update
CiliumPodIPPool resources from Golang, because Golang uses a zero-valued
default struct for the IPv4 or IPv6 fields, which in turn causes
validation errors because the required fields within the IPv4/IPv6
struct where now zero/empty.

For example, if one created an IPv4 only pool:
```
error: CiliumPodIPPool.cilium.io "default" is invalid: [
    spec.ipv6.maskSize: Invalid value:0: spec.ipv6.maskSize in body should be greater than or equal to 1,
    spec.ipv6.cidrs: Required value
]
```

This commit also changes the integer size of the mask size field to a
more appropriate width.

Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>