kvstore: fix TestWorkqueueSyncStoreMetrics flake
This commit addresses a flake observed in the CI:

Error Trace:	/home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/store/syncstore_test.go:392
Error:      	Not equal:
              	expected: 1
             	actual  : 2
Test:       	TestWorkqueueSyncStoreMetrics

This flake was caused by a race condition concerning setting and reading
the metric, and it is addressed asserting that the metric *eventually*
matches the expected value.

Additionally, all timeouts are raised to prevent the occurrence of flakes
when running in a noisy CI environment.

Signed-off-by: Marco Iorio <marco.iorio@isovalent.com>