bpf: fix: Simplify and fix test structure validation logic
Simplify the logic a bit to get rid of the secondary regex match inside
checkProgExists and instead defer the existence check for
progs.checkProg until after the first pass. Just ensure uniqueness of
each setup/pktgen/check program along the way with checkProgUnique.
Before, the logic would not catch if a check is not defined for a test
until later when a panic occurs, since progs.checkProg would be nil, but
now existence of a CHECK program is enforced.

BEFORE
======

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7db080]

goroutine 844 [running]:
testing.tRunner.func1.2({0x2a02a40, 0x4ef3880})
	/usr/local/go/src/testing/testing.go:1734 +0x21c
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1737 +0x35e
panic({0x2a02a40?, 0x4ef3880?})
	/usr/local/go/src/runtime/panic.go:792 +0x132
github.com/cilium/ebpf.(*Program).Type(0x4e5f5a0?)
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/prog.go:573
github.com/cilium/cilium/bpf/tests/bpftest.loadAndRunSpec.subTest.func4(0xc0007028c0)
	/go/src/github.com/cilium/cilium/bpf/tests/bpftest/bpf_test.go:334 +0x9a
testing.tRunner(0xc0007028c0, 0xc0008eb230)
	/usr/local/go/src/testing/testing.go:1792 +0xf4
created by testing.(*T).Run in goroutine 973
	/usr/local/go/src/testing/testing.go:1851 +0x413
FAIL	github.com/cilium/cilium/bpf/tests/bpftest	8.257s

AFTER
=====

--- FAIL: TestBPF (20.63s)
--- FAIL: TestBPF/skip_tunnel_nodeport_nat.o (0.21s)

    bpf_test.go:224: ... does not contain a check program for the ... test.

Don't rely on the program name at all, only the section names. Before,
weird edge cases could occur with strings.Replace() if the test program
name itself had the words "setup", "pktgen", or "check" in them. This
change uncovered the case with nat4_port_allocation where the test name
in the CHECK for the nat4_port_allocation_tcp and
nat4_port_allocation_udp tests was wrong, so fix this.

Signed-off-by: Jordan Rife <jrife@google.com>