proxy: fix test build in v1.8 branch
The respective tests were removed from master in commit 03777e0ce0f1
("proxy: Move Kafka proxy to Envoy Go extensions").

This fixes the following test build failure:

./kafka_test.go:112:2: cannot use &proxyUpdaterMock literal (type *proxyUpdaterMock) as type logger.EndpointUpdater in assignment:
	*proxyUpdaterMock does not implement logger.EndpointUpdater (missing GetNamedPortLocked method)
./mock_test.go:49:42: undefined: policy.NamedPortsMap
FAIL	github.com/cilium/cilium/pkg/proxy [build failed]

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>