test: bpf: Fix load for cgroups progs
[ upstream commit b4cd2bceb95af789a8cea24e9241d3799875e752 ]

Fix the following failure:

    $ TC=/path/to/cilium/tc/binary sudo -E test/bpf/verifier-test.sh
    ...
    => Loading sockops/bpf_sockops.c:sockops...
    ...
    Error: unable to find map 'test_cilium_signals

Signed-off-by: Joe Stringer <joe@cilium.io>
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>