k8s: Workaround flake in TestStateDBReflector
A timing bug in closing of the table init channel
is sometimes causing the test to fail:

  statedb_test.go:263:
     Error Trace:    /.../pkg/k8s/statedb_test.go:263
                     /.../pkg/k8s/statedb_test.go:133
     Error:          Not equal:
                     expected: "obj1"
                     actual  : "garbage"

                     Diff:
                     --- Expected
                     +++ Actual
                     @@ -1 +1 @@
                     -obj1
                     +garbage
     Test:           TestStateDBReflector/TransformMany-QueryAll
  FAIL

The root cause for this is a bug in StateDB that causes
the init watch channel to be closed too early. This
is fixed in https://github.com/cilium/statedb/pull/53.

As it takes a bit of time until we've bumped the StateDB
version, work around this issue by repeatedly checking
if the table is initialized, so folks aren't exposed
to the flake.

Signed-off-by: Jussi Maki <jussi@isovalent.com>