bpf: fix tc_nodeport_lb4_nat_lb
The tc_nodeport_lb4_nat_lb might fail with

   --- FAIL: TestBPF/tc_nodeport_lb4_nat_lb.o (0.01s)
        bpf_test.go:172: loading collection: inlining global data: global constants must be in .rodata.config, but found reference to .bss

if SECLABEL is used inside lib/nodeport.h as an initializer for a variable.
Fix this by defining SECLABEL as an int for the test.

Signed-off-by: Anton Protopopov <aspsk@isovalent.com>
Signed-off-by: Gilberto Bertin <jibi@cilium.io>