clustermesh: fix pattern to match IPv4 address
[ cherry-picked from cilium/cilium-cli repository ]

Executing `cilium clustermesh vm install install-external-workload.sh`
fails if the randomly generated IP (v4) contains a zero (`0`) in its
first byte.

Error: `Malformed CLUSTER_ADDR: 104.198.85.126:2379`

Therefore, this commit changes the pattern that is used to detect
an IPv4 address (with port).

Signed-off-by: Marco Hofstetter <marco.hofstetter@isovalent.com>